#pragma once
#define APP_WIFI_SSID "YOUR_WIFI_SSID"
#define APP_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define APP_XFYUN_APP_ID "YOUR_XFYUN_APP_ID"
#define APP_XFYUN_API_KEY "YOUR_XFYUN_API_KEY"
#define APP_XFYUN_API_SECRET "YOUR_XFYUN_API_SECRET"
#define APP_SONG_LIBRARY_BASE_URL "http://YOUR_ORANGE_PI_IP:8040"
